### ISSUE TITLE
Option to scale to fit

### ISSUE THREAD

**Issue by mavalon** [ivmarcos/react-to-pdf#13]
Is there any way to scale the rendered image down to fit the page?  (Note: even the demo at https://codesandbox.io/s/l2l4pz0jyl only renders a portion of the canvas, and renders differently at different screen resolutions / browser sizes.)

**Comment by bhattiasad99** [comment]
@ivmarcos how did you fix it? I need help, because my image is not scaling properly

**Comment by vishal30982** [comment]
![Image](https://github.com/user-attachments/assets/e0dbd76c-956c-4b30-9506-13e225917e89)
also mine
