### ISSUE TITLE
how to disable to content and only option to download

### ISSUE THREAD

**Issue by cullsin** [ivmarcos/react-to-pdf#14]
Hi,

I have a requirement to hide the view and the user must have an option to download.  Can you please suggest the appropriate tags for that.

thanks,
Raja K

**Comment by ivmarcos** [comment]
sorry @cullsin, I didn't understand what you want to do. maybe putting an overlay in front of the element, is that it?

**Comment by ivmarcos** [comment]
closing due lack of response.
