### ISSUE TITLE
Scaling error on generate file .

### ISSUE THREAD

**Issue by manudevcode** [ivmarcos/react-to-pdf#15]
Some times the PDF is generated with an escalation, which sometimes leaves the PDF, this changes depending on the size and redemption of the screen.
 
Images of the code in sandbox that have in the documentation: 

<img width="1440" alt="Captura de Pantalla 2020-03-04 a la(s) 23 31 29" src="https://user-images.githubusercontent.com/11260098/75950941-47aba200-5e70-11ea-83ae-1db401d85d89.png">

<img width="1440" alt="Captura de Pantalla 2020-03-04 a la(s) 23 32 21" src="https://user-images.githubusercontent.com/11260098/75950994-66aa3400-5e70-11ea-89de-909fb501aeb3.png">

**Comment by phoenixTW** [comment]
I am also facing the similar issue. Is there any solution to it?

**Comment by ivmarcos** [comment]
seems to be a issue related to html2canvas, looking for possible solutions

**Comment by de-ocampo** [comment]
Also hitting the same issue. Having a really hard time figuring out how to get the scaling right.

**Comment by Paa-Kwesi** [comment]
Any update on the fix for this issue?

**Comment by ac4medeveloper** [comment]
I am also facing same issue, please do update 
https://codesandbox.io/s/gracious-cannon-ubfc5

**Comment by ivmarcos** [comment]
fixed in v.0.0.11
