### ISSUE TITLE
Convert only One Page

### ISSUE THREAD

**Issue by Imam-N** [ivmarcos/react-to-pdf#16]
Hi ,

I am converting the Invoice Page to Pdf using react-to-pdf plugin.
Its Converted Particular Height of the Page Only.My Invoice Contains Two Number of Pages.
But this plugin only Convert a single Page with the Paticular Height.

**Comment by kishore075** [comment]
Hey i cannot even install the react-to-pdf my npm command failes with error can you help npm install react-to-pdf

**Comment by ivmarcos** [comment]
@Imam-N as mentioned in readme, only single page supported at the moment, sorry. As alternative, you can try using html2canvas and jsPdf by your own.
