### ISSUE TITLE
Error: "undefined ls-remote -h -t ssh://git@github.com/eligrey/FileSaver.js.git"

### ISSUE THREAD

**Issue by kishore075** [ivmarcos/react-to-pdf#17]
Hi I am getting error at step 1 while installing npm install react-to-pdf cannot install Error: "undefined ls-remote -h -t ssh://git@github.com/eligrey/FileSaver.js.git", can you please help

**Comment by ivmarcos** [comment]
@kishore075 sorry for the delay, seems not to be a problem with the library, but with the npm repository or something else. Tried here, everything ok.
