### ISSUE TITLE
My PDF is getting cut off

### ISSUE THREAD

**Issue by arhoy** [ivmarcos/react-to-pdf#18]
I have the following code

```
import Pdf from 'react-to-pdf'
...
return (
 <Layout>
      <Pdf targetRef={ref} filename="code-example.pdf">
        {({ toPdf }) => <Button onClick={toPdf}>Generate Pdf</Button>}
      </Pdf>
      <Container ref={ref}>
        <Section0 fluid={data.resumePic.childImageSharp.fluid} />
        <Section1 />
      </Container>
    </Layout>
)
```

my PDF keeps getting cut off in width though. Ie. it only shows the left half of the page that is contained inside container...
How can I fix this?

**Comment by ivmarcos** [comment]
@arhoy you can try using the props *scale* to reduce the image size, ex:

```jsx
<Pdf scale={0.5} {...otherProps}>{...}
```

**Comment by arhoy** [comment]
thanks that sort of works but now everything is sort of to the left Also when I pass in the options I get no pdf, ie something breaks
Are you able to assist with that. I am just trying to do something fairly simple in that the it pdf should be in the center and not cut off

Thanks.
Here is my repo if that helps!
https://github.com/arhoy/resume-builder/blob/master/src/pages/resume-gatsby.js

**Comment by arhoy** [comment]
Also even if I scale it gets cut off
![even-if-scale-gets-cut-off](https://user-images.githubusercontent.com/10405245/80027972-a7522100-84a1-11ea-8fda-5e42978fdb54.PNG)

**Comment by ivmarcos** [comment]
centering could be done using *x* or *options* props, which are passed to the jspdf document, as for the cutting issue, can you provide a codesandbox reproducing the problem?

**Comment by arhoy** [comment]
SUre,
https://codesandbox.io/s/github/arhoy/resume-builder?file=/src/pages/index.js

Thanks!

**Comment by arhoy** [comment]
any luck?
