### ISSUE TITLE
pdf quality issue

### ISSUE THREAD

**Issue by chamodKanishka** [ivmarcos/react-to-pdf#19]
actually, this was not an issue. I like this library a lot. but in here I mention that downloaded pdf files characters are with some kind of blur or less quality issu. can you fix it up

**Comment by ivmarcos** [comment]
@chamodKanishka this happens because the pdf is not vectorized, as mentioned in readme. You can try increasing the *scale* prop and/or adjusting the page size using the *options* prop. If that doesn't work, use html2canvas and jspdf manually.
