### ISSUE TITLE
Create a pdf without display the content

### ISSUE THREAD

**Issue by MGMehdi** [ivmarcos/react-to-pdf#22]
Hi, 

is it possible to download a PDF from an external component without mounting it ?

**Comment by hrkazemi** [comment]
for me, it creates a pdf without content and it's in `dom` and also visible.

**Comment by ivmarcos** [comment]
@MGMehdi not, 

> Hi,
> 
> is it possible to download a PDF from an external component without mounting it ?

No, it needs to be mounted, since it uses html2canvas behind.

**Comment by ivmarcos** [comment]
> for me, it creates a pdf without content and it's in `dom` and also visible.

@hrkazemi please try the lastest version, v.0.0.12.
