### ISSUE TITLE
render pdf in list

### ISSUE THREAD

**Issue by vladcom** [ivmarcos/react-to-pdf#26]
Hi. I have a list with 50> items. In each item I have a some unique information and button "Print me". 
If I try download/print first item - everything is ok. But if i try download/print second item I got white area in a top, (100-200px maybe)
If I try download/print tenth item(for example), i got white page.

Maybe you know what is wrong with it? 

Thank you)

**Comment by vladcom** [comment]
@ivmarcos I found out that the display in the pdf file depends on the scroll. but did not find how to fix it yet

**Comment by ivmarcos** [comment]
@vladcom could you please provide a codesandbox showing the issue?

**Comment by ivmarcos** [comment]
Closing due lack of response.
