### ISSUE TITLE
Got Unexpected token: keyword «const» error while running gulp

### ISSUE THREAD

**Issue by sadish-hub** [ivmarcos/react-to-pdf#27]
I received " from UglifyJs
Unexpected token: keyword «const»" error while running gulp. Do you have transpiled ES5 version?

**Comment by ivmarcos** [comment]
@sadish-hub it is already in es5, (index.js and lib/index.js).

**Comment by sadish-hub** [comment]
@ivmarcos  const index = require('./lib'); in index.js has problems with Uglify.js The const to be specific. I might be wrong here as well.

**Comment by ivmarcos** [comment]
@sadish-hub sorry, but there is no *const* in that file (https://github.com/ivmarcos/react-to-pdf/blob/master/lib/index.js), maybe it is some uglify config related?

**Comment by sadish-hub** [comment]
@ivmarcos  Can you check this? https://github.com/ivmarcos/react-to-pdf/blob/master/index.js

**Comment by ivmarcos** [comment]
Fixed in #33, v0.0.12.
