### ISSUE TITLE
How to upload the generated pdf to server?

### ISSUE THREAD

**Issue by bamtanh** [ivmarcos/react-to-pdf#29]
Thank you for providing awesome plugin.
I really like this package.
just I want to upload the generated pdf to my server so that I can send pdf via email.
Is it possible?

**Comment by ivmarcos** [comment]
@bamtanh not possible, at least in the moment. You could try, though, using html2canvas and jsPdf directly to then create a blob and post to your server.

**Comment by guybridge** [comment]
`      const document = await generatePDF(pdfRef, { filename: `report${new Date().toISOString()}.pdf`, method: "build" })
      const base64 = document.output("datauristring")
      console.log(base64)`
