### ISSUE TITLE
Cannot make pdf full width

### ISSUE THREAD

**Issue by bashleigh** [ivmarcos/react-to-pdf#3]
Hey! really liking this package :) Found a bit of an issue though and I'm not sure how to combat it. 

So I've been trying to get my react component page to react full height and width of the PDF. This is an example of my code 

```rxjs
<div className="options">
          <Pdf targetRef={ref} filename="invoice.pdf" options={{
            orientation: 'p',
            unit: 'px',
            format: [595, 842],
          }}>
            {({ toPdf }) => <button onClick={toPdf}>Generate Pdf</button>}
          </Pdf>
        </div>
        <div className="innerDoc" ref={ref}>
          <div className="section">
            <div className="columns">
              <div className="column">
                <h3 className="title is-size-7">From</h3>
                <p>Test</p>
                <p>Test Test</p>
                <p>jk hgf jk</p>
                <p>Rayjkhjkleigh</p>
                <p>jhj</p>
                <p>TEst</p>
              </div>
              <div className="column">
                <h3 className="title is-size-7">For</h3>
                <p>jjh jhk jkh</p>
                <p>jkjkhhj jk kj</p>
                <p>jkh</p>
                <p>kjhj kjhkjh</p>
              </div>
              <div className="column">
                <h5 className="title is-size-7">Details</h5>
                <p>Date: 14/02/19</p>
                <p>Due Date: 28/02/19</p>
                <p>Invoice No: A001001</p>
              </div>
            </div>
            
            <table className="table is-fullwidth">
              <tr>
                <th>Item no</th>
                <th>Description</th>
                <th>Quantity</th>
                <th>Unit Price</th>
                <th>Amount</th>
              </tr>
              <tr>
                <td></td>
                <td>Jeff</td>
                <td>3</td>
                <td>&pound;20</td>
                <td>&pound;60</td>
              </tr>
              <tr>
                <td></td>
                <td>Bob</td>
                <td>1</td>
                <td>&pound;10</td>
                <td>&pound;10</td>
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td colSpan="4" style={{textAlign: 'right'}}>Sub total</td>
                <td>&pound;70</td>
              </tr>
              <tr>
                <td colSpan="4" style={{textAlign: 'right'}}>Discount</td>
                <td>0%</td>
              </tr>
              <tr>
                <td colSpan="4" style={{textAlign: 'right'}}>Amount Due</td>
                <td>&pound;70</td>
              </tr>
            </table>
            <hr />
            <h3 className="title is-size-7">Notes</h3>
            <p className="notes"></p>
          </div>
        </div>
```
this is the result of my react component. the `.innerDoc` class is 595px wide by 842px high. 
![screenshot 2019-02-15 at 14 18 19](https://user-images.githubusercontent.com/11574250/52862417-296fe880-312d-11e9-8e0f-a514e4a49b23.png)

When generating my PDF I can't seem to make my component react full width or height of the PDF? 
![screenshot 2019-02-15 at 14 18 33](https://user-images.githubusercontent.com/11574250/52862487-4d332e80-312d-11e9-88d8-f6483d512d92.png)

Any ideas how I can resolve this? I haven't yet dived into your package code. Thought I'd best ask first

**Comment by bashleigh** [comment]
So after having a quick check I can see that you're creating a canvas image of the given referenced DOM element and adding that to jsPDF. https://github.com/ivmarcos/react-to-pdf/blob/master/src/index.jsx#L23

Looks like you can add a width and height to the image. Finding the correct width and height to apply would fix my issue :) I'm guessing there must be a way of obtaining the width and height from jsPDF and applying that to the addImage method?

**Comment by bashleigh** [comment]
Ok so, sorry for another comment. 

I managed to get this working by manipulating the line mentioned above to the following

```js
const pdf = new JsPdf(options);
pdf.addImage(imgData, 'JPEG', x, y, pdf.internal.pageSize.getWidth(), pdf.internal.pageSize.getHeight());
```
This does fix this issue; I'll open a PR. However the image is slightly blurry but it is full width + height.

**Comment by ivmarcos** [comment]
Hi @bashleigh, glad you liked it :smiley:! This lib is really in the beginning and it is still necessary, in some cases, to customize the pdf output using the options props. It's just a wrapper using the incredible html2canvas and the fantastic jspdf and I'll release soon some other options to allow a refinement of this customization in a easy way.
PR is always welcome! Feel free to submit at any time. The blurred image is a well-known problem and is due to the canvas. Until I release more options in an upcoming release, you could try using yourself html2canvas and jsPdf with the option ```{scale: 2}```, below an example:

```
html2canvas(ref.current, {scale: 2}).then(canvas => {
//...generate pdf using jsPdf
}) 
```

**Comment by bashleigh** [comment]
@ivmarcos ok cool :) Have you already started on the new release? Would you like some help?

**Comment by ivmarcos** [comment]
Definitely, it would be awesome! At the moment I have some ideas that would be nice to support, such as multi-page, testing, an easy implementation for props such as page orientation, margin and resolution, often used. I've created the next branch for this and if you're interested, I can add you as a collaborator or you can as before send PRs, just let me know okay.

**Comment by bashleigh** [comment]
yea that sounds cool :) if you make a project on github with a kanban and assign issues to me I'll give them a go :) up to you. I can always fork and PR? 

Still not sure whether to make a PR for what I did recently? I suppose you've seen the fork I've made? https://github.com/ivmarcos/react-to-pdf/compare/master...bashleigh:feature/fullwidth I know you was talking about parameters and options to add. 

Testing would be really good! Currently I'm using yalc to add my package locally to a service I've created and editing and updating their to see changes

**Comment by ivmarcos** [comment]
I'd rather you make a PR for the [next](https://github.com/ivmarcos/react-to-pdf/tree/next) branch, because full width is something I see as an option or a strategy to render the pdf in a deliberated way. I did see your fork, nice job! I'll then create a project as you suggested.

**Comment by bashleigh** [comment]
cool will do, I'll check it out now. Yea I wasn't sure if that was right doing that. It fixes my issue but obviously it's a bit opinionated

**Comment by vitaliysobur** [comment]
hi @ivmarcos @bashleigh thank you for your work on this project. I was wondering if it is going to move forward or you have some other plans for the evolution of this module? I see the card is created and now sits in the "To Do" column.

**Comment by ivmarcos** [comment]
Sorry @bashleigh and @vitaliysobur , I've been extremely busy and could not contribute much these last months. After thinking about it, I've decided not to support multiple pages for two reasons: first, the process of transforming html to canvas and then into base64 when using large size elements could make it unusable, it can easily exceed 2-3mb when using high resolution over 3 pages (letter/a4 pages, for example); second, the possibility of using different options in jspdf makes the implementation too complex to estimate how many pages will be necessary to render. You can @vitaliysobur, nevertheless, as I suggested before, use directly html2tocanvas with jspdf or, which I encourage, use [react-pdf/renderer](https://www.npmjs.com/package/@react-pdf/renderer) to achieve vectorized documents, which will produce better results.
