### ISSUE TITLE
Iframe inside div is not getting captured

### ISSUE THREAD

**Issue by rahulsingh806080** [ivmarcos/react-to-pdf#36]
Iframe inside div is not getting captured. to avoid cors i deployed iframe on localhost:8000 and my code is on localhost:5000
In screenshot u can see blue color is div inside that iframe( localhost:8000 ) is there. only div is getting captured with blue color not iframe contents

<img width="1429" alt="Screen Shot 2020-09-24 at 2 39 18 AM" src="https://user-images.githubusercontent.com/16794968/94070176-658e2380-fe0f-11ea-9a4e-3848cca77b32.png">

**Comment by ivmarcos** [comment]
@rahulsingh806080 please provide a codesandbox or jsfiddle showing the issue.
