### ISSUE TITLE
Element is not attached to a Document

### ISSUE THREAD

**Issue by VeerneToor** [ivmarcos/react-to-pdf#37]

**Comment by VeerneToor** [comment]
![image](https://user-images.githubusercontent.com/48494332/94314668-9d4bb700-ff46-11ea-9a23-b9da0091621e.png)

**Comment by VeerneToor** [comment]
![image](https://user-images.githubusercontent.com/48494332/94314731-c5d3b100-ff46-11ea-825b-cbd4e7740e48.png)

**Comment by ivmarcos** [comment]
@VeerneToor please provide a codesandbox or jsfiddle showing the issue.

**Comment by madiyar** [comment]
I caught same error. I wrapped component to div element with ref and it works. 
`<div ref={pdfRef}>
    <ReactComponent ... />
</div>`

**Comment by cderche** [comment]
@madiyar could you please provide an example. Thank you.

**Comment by rootical** [comment]
It happens when you pass a `ref` around. In order to do that you should use `forwardRef` for example.

**Comment by ralphvirtucio** [comment]
Hi, @VeerneToor, Did you solve this issue already ?
