### ISSUE TITLE
Generating Blank pdf file

### ISSUE THREAD

**Issue by muhammadowaiswarsi** [ivmarcos/react-to-pdf#39]
when i click on export button library generates blank pdf file

`<ReactToPdf
                      targetRef={reference1}
                      x={5}
                      y={5}
                      scale={1}
                      filename="my-stocks.pdf"
                      options={pdfOptions}
                    >
                      {({ toPdf }) => (
                        <IconButton
                          onClick={toPdf}
                          reactIcon={
                            <AiOutlineImport className="orange-icon-btn" />
                          }
                          className="orange-react-icon"
                          btnText="Export File"
                        />
                      )}
                    </ReactToPdf>`

`<div className="my-stock-table" ref={reference1}>
              <StockTable
                loading={allPortfolio}
                id={portfolio?.id}
                OnDelete={DeleteSymbol}
                stock={portfolio}
              />
             </div>`

**Comment by sahaditya** [comment]
> when i click on export button library generates blank pdf file
> 
> `<ReactToPdf targetRef={reference1} x={5} y={5} scale={1} filename="my-stocks.pdf" options={pdfOptions} > {({ toPdf }) => ( <IconButton onClick={toPdf} reactIcon={ <AiOutlineImport className="orange-icon-btn" /> } className="orange-react-icon" btnText="Export File" /> )} </ReactToPdf>`
> 
> `<div className="my-stock-table" ref={reference1}> <StockTable loading={allPortfolio} id={portfolio?.id} OnDelete={DeleteSymbol} stock={portfolio} /> </div>`

I am also facing the same issue if I add the options props

**Comment by tristanhcole** [comment]
If you do don't use format, it seems to work for me  
```js
const options = {
    orientation: "landscape",
    unit: "in"
  };
```

**Comment by ivmarcos** [comment]
If the format does not work please reopen this.

**Comment by pranav-inaira** [comment]
same issue happening for me.
Webpack 4
React 18

"react-scripts": "^4.0.3",
 "react-to-pdf": "^1.0.1",
"react": "^18.2.0",

Running on CRACO,

module.exports = {
    babel: {
        plugins: [
            "@babel/plugin-proposal-nullish-coalescing-operator",
            "@babel/plugin-proposal-optional-chaining"
        ]
    }
};
