### ISSUE TITLE
error when installing react-to-pdf package

### ISSUE THREAD

**Issue by Mary19Star** [ivmarcos/react-to-pdf#40]
when i try to install react-to-pdf package using this command : npm install react-to-pdf
i get this errors :

```
npm ERR! code ENOENT 
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/eligrey/FileSaver.js.git
npm ERR! enoent 
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```
could someone tell me what the problem is ?

**Comment by baelter** [comment]
Still an issue: https://github.com/ivmarcos/react-to-pdf/issues/17

**Comment by rafioktavian** [comment]
i have same problem, i found error when installing this plugin

**Comment by ivmarcos** [comment]
Not being able to reproduce. Used `yarn install react-to-pdf@latest` and `npm install react-to-pdf@0.0.14`

**Comment by baelter** [comment]
Worked around it by adding this to our `package.json`
```
"scripts": {
  "heroku-prebuild": "git config --global url.\"https://github.com/\".insteadOf git@github.com: && git config --global url.\"https://\".insteadOf ssh://"
}
```

**Comment by mmozammel99** [comment]
npm i react-to-pdf --f try this

**Comment by sabbir1020** [comment]
same problem

**Comment by ehasanulh1** [comment]
I also face the same issue.

**Comment by ivmarcos** [comment]
Please check if the problem persists with V1, not being able to reproduce. Closing this but feel free to open another issue if that continues with the newest releases.
