### ISSUE TITLE
blank pdf generated  in production 

### ISSUE THREAD

**Issue by Razi321** [ivmarcos/react-to-pdf#44]
in development  everything work fine but in production i only see a blank page 

```
const ref = React.createRef();

<div>
// code of the ui that will be printed 
</div>

<Pdf targetRef={ref} filename="code-example.pdf">
        {({ toPdf }) => <button onClick={toPdf}>Generate Pdf</button>}
 </Pdf>
```

Development : 
<img width="1792" alt="Screen Shot 2021-01-16 at 16 54 32" src="https://user-images.githubusercontent.com/38192665/104806731-ffde0100-581c-11eb-8ea0-f2ef3f1cb2c2.png">

Production : 
<img width="1792" alt="Screen Shot 2021-01-16 at 16 54 41" src="https://user-images.githubusercontent.com/38192665/104806742-0d938680-581d-11eb-8dd7-d81c6e09da28.png">

**Comment by ivmarcos** [comment]
Try using the latest version, probably some html2canvas dependency related https://github.com/ivmarcos/react-to-pdf/releases/tag/0.0.14

**Comment by pranav-inaira** [comment]
I'm getting blank PDF even in development mode, Webpack 4.
