### ISSUE TITLE
xmldom needs an update

### ISSUE THREAD

**Issue by philbert440** [ivmarcos/react-to-pdf#48]
=== npm audit security report ===                        

                                 Manual Review                                  
             Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           

  Low             Misinterpretation of malicious XML input                      

  Package         xmldom                                                        

  Patched in      >=0.5.0

  Dependency of   react-to-pdf

  Path            react-to-pdf > jspdf > canvg > xmldom

  More info       https://nodesecurity.io/advisories/1650

**Comment by philbert440** [comment]
![image](https://user-images.githubusercontent.com/7538030/115081442-44d40b00-9ed2-11eb-9586-4ff6828c1aa0.png)

**Comment by ivmarcos** [comment]
Should be fixed in https://github.com/ivmarcos/react-to-pdf/releases/tag/0.0.14
