### ISSUE TITLE
Unit/format options not working

### ISSUE THREAD

**Issue by ClydSpyd** [ivmarcos/react-to-pdf#49]
Hello.

I love this tool, it really helped me out with a feature I was working on, so thanks a lot!

One issue I'm having is that the 'unit'/'format' keys on the settings object do not seem to be having the desired effect. I keep getting tiny little files rather than the measurements I input.

Here's an example:

```
<Pdf 
  options={{
    orientation:"landscape", 
    unit:"in", format:[cover_width, cover_height]
   }} 
   onComplete={()=>setLoading(false)} 
   targetRef={ref} 
   filename={`${projectTitle}_cover.pdf`}>
```

The input values are:
cover_width: 12.316756756756757
cover_height: 9.25

It is orientated correctly, document is 0.43cm x 0.43cm!

Any ideas what I'm doing wrong??

Many thanks

**Comment by ivmarcos** [comment]
Not sure if that matters now due to the time elapsed - and my apologies for that - otherwise check if the problem persists with v1. Closing this, but feel free to open another issue.
