### ISSUE TITLE
Left side is offset and right side is cut off

### ISSUE THREAD

**Issue by iamsajithsasi** [ivmarcos/react-to-pdf#52]
I forked sample sandbox given in the readme and generated pdf. But, texts got cut off and its was off the alignment. 

I referred and added CSS properties to match a4 paper size and it rendered pdf. But, still there is a offset in the left side with white space and right side is cut off.

![image](https://user-images.githubusercontent.com/59168331/119690973-cd49b200-be67-11eb-83f1-d84ec04bb773.png)

How could this be rectified so that the content is not lost.

Forked and edited sandbox [Link](https://codesandbox.io/s/sweet-mirzakhani-gbuig?file=/src/index.js)

Forked [URL](https://gbuig.csb.app/)

**Comment by ivmarcos** [comment]
Sorry for the delay in the response, if that still matters at the moment, check with the newest releases (v1 for example) if the problem persists. Closing this but feel free to open another issue.
