### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by pnyennhi** [ivmarcos/react-to-pdf#54]
I've accessed this example link but it seemed not to be working. Nothing happened when I clicked `Generate Pdf` button.
[https://codesandbox.io/s/l2l4pz0jyl](https://codesandbox.io/s/l2l4pz0jyl)

Could you please give me a working one?

**Comment by crscaballero** [comment]
I've changed the `Pdf` to use `ReactToPdf` and that worked for me

https://codesandbox.io/s/optimistic-chatelet-w8p6y
