### ISSUE TITLE
Using react-to-pdf with typescript

### ISSUE THREAD

**Issue by olabamipetaiwo** [ivmarcos/react-to-pdf#57]
This package doesn't have a types file to use with typ[escript

**Comment by loki344** [comment]
Any news on this?

**Comment by israelitalo** [comment]
Has anyone managed to solve this problem?

**Comment by sajeebmahamed** [comment]
I solve this issue. Firstly, Create a folder **typings** then create file **index.d.ts** inside the folder. then declare module `declare module 'react-to-pdf'`. Then add `"typeRoots": [
        "./typings",
        "./node_modules/@types"
    ]` inside tsconfig.json.
    
 Folder Structure:

-  typings
   - index.d.ts
     `declare module 'react-to-pdf'

![ts-config](https://user-images.githubusercontent.com/40857369/203737438-08f42e57-ce4d-4ddd-b3f6-ac67d505b183.png)
rror-ts7016-could-not-find-a-declaration-file-for-module-xyz-has-an-any-type-ecab588800a8)

[Reference](https://pjausovec.medium.com/how-to-fix-e

**Comment by Auspicious14** [comment]
> I solve this issue. Firstly, Create a folder **typings** then create file **index.d.ts** inside the folder. then declare module `declare module 'react-to-pdf'`. Then add `"typeRoots": [ "./typings", "./node_modules/@types" ]` inside tsconfig.json.
> 
> Folder Structure:
> 
> * typings
>   
>   * index.d.ts
>     `declare module 'react-to-pdf'
> 
> ![ts-config](https://user-images.githubusercontent.com/40857369/203737438-08f42e57-ce4d-4ddd-b3f6-ac67d505b183.png) rror-ts7016-could-not-find-a-declaration-file-for-module-xyz-has-an-any-type-ecab588800a8)
> 
> [Reference](https://pjausovec.medium.com/how-to-fix-e

This doesn't work for me

**Comment by Auspicious14** [comment]
It works now but there's still error in the code as {toPdf} still has an implicit type of any with red underline

**Comment by meessour** [comment]
Try declaring a module like this:

`declare module 'react-to-pdf' {
    import { RefObject } from 'react';

    function ReactToPdf(
        targetRef?: RefObject,
        filename?: string,
        x?: number,
        y?: number,
        options?: object,
        onComplete?: function,
        scale: number
    ): ReactNode<{ toPdf: () => void; targetRef: MutableRefObject }>;

    export = ReactToPdf;
}`

**Comment by ivmarcos** [comment]
v1 has been just released and it's built with TS, please  see README for more details/examples.
