### ISSUE TITLE
React 17 compatibility

### ISSUE THREAD

**Issue by calebchiam** [ivmarcos/react-to-pdf#58]
Hi! Thanks for this very useful package. I was wondering, do you have any plans to make this compatible with React 17?

**Comment by dudusohne** [comment]
it's not?

**Comment by svandegar** [comment]
@Knapsack123 , I tried it but seems to be only compatible with React 18, not 17.

**Comment by ivmarcos** [comment]
v1 has just been released supporting react > 16.8
