### ISSUE TITLE
After generate PDF texts are getting blurred

### ISSUE THREAD

**Issue by LenaHovhannisyan** [ivmarcos/react-to-pdf#60]
When I generated pdf files it showed texts blurred

**Comment by alikarani** [comment]
use scale property to fix it.

**Comment by Rishav-264** [comment]
@alikarani scale property is not fixing it, its just changing the size and things are still blurry, could you offer some more assistance?

**Comment by ivmarcos** [comment]
FYI v1 has been released supporting the `resolution` param but even with the default config you should get a reasonable text resolution. See examples on README 🙂 .
