### ISSUE TITLE
Would like to have setDisplayMode "continuous"

### ISSUE THREAD

**Issue by alvarosalas** [ivmarcos/react-to-pdf#66]
This is not an issue but it would be nice to have setDisplayMode for this npm

**Comment by usfslk** [comment]
Did you manage to show multiple pages? if so how? For me it only showing 1 page and rest of the content is cropped

**Comment by Safnaj** [comment]
I am facing the same issue. Is A4 is fixed ? can't we change the size ?

**Comment by ivmarcos** [comment]
Sorry for the delay in the response here. Not sure what is the issue here, but v1 has been released with some new features including multipage support. Closing this but feel free to open another issue if the issue persists.
