### ISSUE TITLE
@viniciushfr  did you find a solution to this problem? Im facing the same issue

### ISSUE THREAD

**Issue by bhattiasad99** [ivmarcos/react-to-pdf#68]
@viniciushfr  did you find a solution to this problem? Im facing the same issue
my svg on page
![image](https://user-images.githubusercontent.com/69630565/192758065-f7c2255f-30aa-4ea4-809b-dc243ce5c726.png)
downloaded file
![image](https://user-images.githubusercontent.com/69630565/192758124-2b7f9725-2c0f-47d7-8f66-c9137639fa3d.png)

_Originally posted by @bhattiasad99 in https://github.com/ivmarcos/react-to-pdf/issues/41#issuecomment-1260715033_

**Comment by ivmarcos** [comment]
Sorry for the delay in the response.Please check using the newest releases (v1) which has upgraded its dependencies (html2canvas and jspdf). Closing this but feel free to open another issue if the problem then continues.
