### ISSUE TITLE
Rendering beyond a single page

### ISSUE THREAD

**Issue by Imam-Abubakar** [ivmarcos/react-to-pdf#69]
Is there a way to have more than a single page document if the content I'm tryna render spans multiple pages?

**Comment by techbot11** [comment]
@Imam-Abubakar did you find any solution for this use case?

**Comment by Imam-Abubakar** [comment]
Nah, I tinkered with it for a bit but it didn’t work as expected…You should just use jspdf

**Comment by techbot11** [comment]
thanks, @Imam-Abubakar for the response.

**Comment by AadarshGhodasara** [comment]
@Imam-Abubakar Do you have proper example of how to use jsPdf for react to pdf?

**Comment by ivmarcos** [comment]
v1 has been released automatically support multipage, please refer to README for more details and examples 🙂 .
