### ISSUE TITLE
Error: Image empty

### ISSUE THREAD

**Issue by longpro1601** [ivmarcos/react-to-pdf#7]
Hi,
I try react-to-pdf,
But I have error about biding image from url (ex: http://domain/static/image.png)
Library convert to pdf, but image cannot biding (mage empty on file PDF).
Please help, fix error .

Thanks.

**Comment by ivmarcos** [comment]
Really sorry about the delay @longpro1601. Could you provide some example using codesandbox?

**Comment by hkayhan** [comment]
https://codesandbox.io/embed/jovial-hellman-k2bn2?fontsize=14&hidenavigation=1&theme=dark

**Comment by tosifkhan01** [comment]
> https://codesandbox.io/embed/jovial-hellman-k2bn2?fontsize=14&hidenavigation=1&theme=dark

Hey @hkayhan Any solution?

**Comment by tosifkhan01** [comment]
> Really sorry about the delay @longpro1601. Could you provide some example using codesandbox?

Hi @ivmarcos ,
I'm facing the same issue.
Can you provide workaround or something?

**Comment by ivmarcos** [comment]
fixed in [v.0.0.10](https://github.com/ivmarcos/react-to-pdf/releases/tag/0.0.10), sample: https://codesandbox.io/s/dank-morning-zcu5i
