### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by WagnerSilveira** [ivmarcos/react-to-pdf#71]
When we will have support for react 18?

**Comment by ishangupta01** [comment]
Any updates on this?

**Comment by isaac1400** [comment]
Any updates on this? How can we help?

**Comment by ZoharHedri** [comment]
Hey,
Just to know the 23 at March passed a long time ago.
Any updates please?
Tnx

**Comment by ivmarcos** [comment]
v1 has just been released supporting react versions > 16.8.
