### ISSUE TITLE
Creating new page

### ISSUE THREAD

**Issue by patrickleemsantos** [ivmarcos/react-to-pdf#8]
How to create a new page if exceeds the height of the page?

**Comment by ivmarcos** [comment]
non-trivial feature, at least for now. studying solutions on how to solve in a simple way in the next version.

**Comment by mathur619** [comment]
Is there a solution for this ??

**Comment by mathur619** [comment]
> How to create a new page if exceeds the height of the page?

You find any solution?

**Comment by ivmarcos** [comment]
v1 has been released with the multipage support, please refer to the https://github.com/ivmarcos/react-to-pdf/blob/main/CHANGELOG.md#100-alpha0-august-26-2023 to see how to migrate from v0 to v1.
