### ISSUE TITLE
Text position different in generated PDF than in component

### ISSUE THREAD

**Issue by siiddhantt** [ivmarcos/react-to-pdf#88]
As seen in the two images, the text has gone down in generated PDF, and this happens with all the texts. 
I'm using React 18.2 (Vite).

Expected : 
![Screenshot from 2023-10-08 23-01-00](https://github.com/ivmarcos/react-to-pdf/assets/47355538/e00c405e-9ab1-4e6b-8edc-668519edb493)

Generated PDF:
![image](https://github.com/ivmarcos/react-to-pdf/assets/47355538/dbfdb709-4ef4-4c66-b46a-f9ec6d737043)

**Comment by ivmarcos** [comment]
I'd guess is due to some CSS and related to the `html2canvas` packaged that is used internally. Hard to say without looking at the code, but here's a similar issue in there: https://github.com/niklasvh/html2canvas/issues/2775.

**Comment by bigyanse** [comment]
I am using TailwindCSS and restoring `img` display attribute to `inline-block` helped me. Check out [this](https://github.com/niklasvh/html2canvas/issues/2775#issuecomment-1204988157) reference.

**Comment by siiddhantt** [comment]
Thanks @ivmarcos and @bigyanse it was indeed the issue with Tailwind. Restoring display attribute to inline-block didn't fix it entirely, so I went ahead with svg components and it fixed the issue throughout the document!

**Comment by charlietlamb** [comment]
Add this in your css file if you are using tailwind:

`@layer base {
  img {
    @apply inline-block;
  }
}`

**Comment by PeterCha90** [comment]
> Add this in your css file if you are using tailwind:
> 
> ```
> @layer base {
>   img {
>     @apply inline-block;
>   }
> }
> ```
> 
> It will fix the issue in html2canvas

You saved my day!! AWESOME!!
