### ISSUE TITLE
Is it possible to create a pdf by hiding content elements?

### ISSUE THREAD

**Issue by woraput** [ivmarcos/react-to-pdf#94]

**Comment by ivmarcos** [comment]
Hi @woraput , do you mean like this?

https://codesandbox.io/s/fast-frost-m43fg7?file=/src/App.tsx

**Comment by woraput** [comment]
Oh absolute yes, Thank you.

**Comment by t3db0t** [comment]
Is there any way to do the opposite: hiding certain components or elements ONLY when being exported to PDF?

**Comment by aaronzhongg** [comment]
@t3db0t you can achieve this using `data-html2canvas-ignore="true"`

https://stackoverflow.com/a/43253745/7577691

**Comment by t3db0t** [comment]
@aaronzhongg Oh amazing, thank you!

**Comment by IzzeRodrigues** [comment]
> Hi @woraput , do you mean like this?
> 
> https://codesandbox.io/s/fast-frost-m43fg7?file=/src/App.tsx

Is there any way to do this in JS?
