### ISSUE TITLE
It is posible to force page break when need?

### ISSUE THREAD

**Issue by woraput** [ivmarcos/react-to-pdf#95]

**Comment by iamtsend** [comment]
@ivmarcos  is it possible to page break?

**Comment by ivmarcos** [comment]
Hum sorry, I don't see how that can be done at the moment. I'm planning to add it as a new feature and that's something I'm working on but I can see no ETA yet.

**Comment by iamtsend** [comment]
At the moment I set fixed height to my container divs. It works fine. But if the page break added, it would be great.

**Comment by woraput** [comment]
Thank you
